### PR TITLE
Membership update: fix form's width auto scaling  with content

### LINKED ISSUE #186: Update membership: fix form'width
On ie form's width scales according to content length

Screen Shot 2019-11-04 at 12 43 29

### PR DESCRIPTION
**Pull request by LouiaR**
Type: patch

Fixes #186

### CODE REVIEW

File: src/components/Molecules/Membership/Form/Form.js [hunk 1]
```diff
@@ -178,7 +178,7 @@ const Signup = ({
         </FormFieldset>
         <Button type="submit">Donate</Button>
         {errorMsg && (
-          <Error>
+          <Error as="p">
```
Comment (gusliedke) [inline src/components/Molecules/Membership/Form/Form.js]: You can use `tag="p"` Error is Text component.

Comment (LouiaR) [reply src/components/Molecules/Membership/Form/Form.js]: Done
