### PR TITLE
Fix/21 more colour variants for links

### LINKED ISSUE #21: Add more colour variations for Link component
And all inline link colours too.

### PR DESCRIPTION
**Pull request by Heleen-cr**
Type: patch

Fixes #21

## Changes proposed in this PR

- [x] add fix in commit message
- add button colour types to theme and use this for links styled as buttons.
- add variations of inline links

### CODE REVIEW

File: src/components/Atoms/Link/Link.js [hunk 1]
```diff
@@ -1,47 +1,45 @@
...
   );
 };
 
 Link.propTypes = {
-  /** Inline is link style */
-  inline: PropTypes.bool,
-  wrapper: PropTypes.bool,
-  /** Button color style */
+  /** Link styling: button, standard, etc. See linkStyles in theme. */
+  linktype: PropTypes.string,
```
Comment (gusliedke) [inline src/components/Atoms/Link/Link.js]: We can define the values `PropTypes.oneOf(['button', 'standard'])`

Comment (gusliedke) [reply src/components/Atoms/Link/Link.js]: I also would just call it `type`.

File: src/components/Atoms/Link/Link.md [hunk 2]
```diff
@@ -1,33 +1,61 @@
...
-    >
-      <a href="#">Link as button</a>
+    <Link href="#anchor" target="blank" linktype="standard">
+      Link standard
     </Link>
   </div>
   <div style={{ display: 'block', marginBottom: '10px' }}>
-    <Link color="red" href="/test" target="self">
-      Link as button
+    <Link href="#anchor" linktype="bold">
```
Comment (gusliedke) [inline src/components/Atoms/Link/Link.md]: Should this be `weight` instead type.

Comment (gusliedke) [reply src/components/Atoms/Link/Link.md]: weight could also be done via `Text`.

Comment (Heleen-cr) [reply src/components/Atoms/Link/Link.md]: yeah that's true. It used to be one of the link types we had and if you'd use the bold class you'd get a bold link you see. I'll remove it and just keep the standard and standard_white link styles 👍

File: src/components/Atoms/Link/Link.js (hunk 1 above)
Comment (Heleen-cr) [reply src/components/Atoms/Link/Link.js]: nice one, will add that

**Comment by Heleen-cr** [comment]
@gusliedke completely forgot to add the transparent button there, will add now.

File: src/theme/crTheme/linkStyles.js [hunk 3]
```diff
@@ -19,6 +19,15 @@ const linkStyles = {
...
+  bold: {
+    color: color('black'),
+    border: `2px solid ${color('black')}`,
+    weight: '700',
+    padding: '0 2px 1px',
+    hoverColor: color('black'),
+    hoverBorder: `2px solid ${color('black')}`,
+    hoverWeight: '800'
   }
 };
```
Comment (LouiaR) [inline src/theme/crTheme/linkStyles.js]: Can we used spacing variant on padding

Comment (Heleen-cr) [reply src/theme/crTheme/linkStyles.js]: like a variable? Not sure what you mean by spacing variant

Comment (LouiaR) [reply src/theme/crTheme/linkStyles.js]: Yep, you can check an example on this file `DoubleCopy.style.js`

Comment (gusliedke) [reply src/theme/crTheme/linkStyles.js]: Yeah, it would be nice for us to start using our `spancing` util. ie.`margin-bottom: ${spacing('sm')};` whenever is possible .. margins between elements is a good case for it. Maybe a bit difficult to apply in button padding for instance.. see where it fits best having in mind we need to stay close to current design.

Comment (Heleen-cr) [reply src/theme/crTheme/linkStyles.js]: ahh ok I see.  I'll have a look to see if it's useful for the link padding. 👍

Comment (Heleen-cr) [reply src/theme/crTheme/linkStyles.js]: myeah so I think it's not useful for the link padding there. Do you guys want me to introduce a margin-bottom with the spacing variable just in case we need to have multiple buttons on top of each other or something?

Comment (gusliedke) [reply src/theme/crTheme/linkStyles.js]: I don't think so, margins around buttons and link will be defined by its "parent" the component that will be using them and sorting their position etc. Ready to merge! :)
