### PR TITLE
fix: #79 - window not defined

### LINKED ISSUE #79: Window is not defined in Gatsby build
Window is not defined in Gatsby build

### PR DESCRIPTION
**Pull request by s-barrah**
Type: patch

Fixes #79 

## Changes proposed in this PR

- Fixes `ReferenceError: window is not defined` during Gatsby build as components are rendered server-side where `window` isn't defined. 
- Solved by accessing `window` after component has mounted or checking if `window` is not `undefined` before accessing it.

### CODE REVIEW

File: src/components/Molecules/Header/Nav/Nav.js [hunk 1]
```diff
@@ -21,16 +21,20 @@ const MainNav = ({ navItems }) => {
...
     event.preventDefault();
     setIsExpandable(!isExpandable);
   };
 
-  // Detect windown screen size
-  const width = window.innerWidth;
-  const mobile = width < sizes.medium;
-
   const toggleSubMenu = item => event => {
     if (mobile) {
```
Comment (LouiaR) [inline src/components/Molecules/Header/Nav/Nav.js]: Nice job @s-barrah, currently toggleBurgerMenu is not working because mobile is set to null

File: src/components/Molecules/Header/Nav/Nav.js [hunk 2]
```diff
@@ -21,16 +21,20 @@ const MainNav = ({ navItems }) => {
   const [isExpandable, setIsExpandable] = useState(false);
   const [isSubMenuOpen, setIsSubMenuOpen] = useState({});
   const [isKeyPressed, setIsKeyPressed] = useState({});
+  let [width] = useState(null);
+  let mobile = useState(false);
+
+  useEffect(() => {
+    // Detect window screen size
+    width = window.innerWidth;
```
Comment (gusliedke) [inline src/components/Molecules/Header/Nav/Nav.js]: wouldn't something like ```width= typeof window !== 'undefined' && window.innerWidth;``` work?

File: src/components/Molecules/Header/Nav/Nav.js [hunk 3]
```diff
@@ -21,16 +21,20 @@ const MainNav = ({ navItems }) => {
   const [isExpandable, setIsExpandable] = useState(false);
   const [isSubMenuOpen, setIsSubMenuOpen] = useState({});
   const [isKeyPressed, setIsKeyPressed] = useState({});
+  let [width] = useState(null);
```
Comment (gusliedke) [inline src/components/Molecules/Header/Nav/Nav.js]: Can we have same as above and better const naming?
```
const [initialWidth, setInitialWidth] = useState(null) // probably we need to set value here for SSR
const [isMobile, setIsMobile] = useState(false);
```

**Comment by gusliedke** [comment]
@LouiaR can you check again if `Header` is still functioning properly with this fix?

**Comment by LouiaR** [comment]
On mobile, when you click to one of the li first level instead to toggle, it redirects you to a new page

**Comment by gusliedke** [comment]
Could you pair with @s-barrah so he knows how to check nav functionality. Maybe a good idea to add some tests checking those toggles.
